### ISSUE TITLE
Legend text in same color as pie chart is unreadable.

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [grafana/piechart-panel#189]
V1.3.8, Grafana 4.6
When placing the legend text on the chart it doesn't make a lot of sense to color it in the same color as the pie chart. the text becomes unreadable! Text should be white or black depending on style.

![image](https://user-images.githubusercontent.com/10830223/63721478-a5bc5480-c851-11e9-9225-a83c4aa91e6d.png)

**Comment by liuyu81** [comment]
Seems like this issue was recently introduced. In V1.3.6 the donut was much thinner, and there was barely overlap with the legend text. See the following comparison,

V1.3.8, Grafana 6.3.3

![WechatIMG269](https://user-images.githubusercontent.com/885656/63744153-0c348780-c8d1-11e9-8a13-7a078baf9ffd.jpeg)

V1.3.6, Grafana 6.2.2

![WechatIMG270](https://user-images.githubusercontent.com/885656/63744163-19ea0d00-c8d1-11e9-8764-67feb5676f95.jpeg)
